dev_queue:
  container_name: dev_queue
  restart: always
  image: kdihalas/beanstalkd:latest
dev_mysql:
  container_name: dev_mysql
  restart: always
  image: mysql/mysql-server:5.6
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_DATABASE=homestead
    - MYSQL_USER=homestead
    - MYSQL_PASSWORD=secret
dev_phpfpm:
  container_name: dev_phpfpm
  restart: always
  image: myphp:apache
  links:
    - dev_mysql:db
    - dev_queue:queue
  environment:
    - DB_HOST=dev_mysql
    - BEANSTALKD_HOST=dev_queue
  volumes:
    - /tmp/laravel_project:/var/project
  working_dir: /var/project
dev_nginx:
  container_name: dev_nginx
  restart: always
  image: nginx:1.9.6
  ports:
    - "80:80"
  links:
    - dev_phpfpm:phpfpm
  volumes:
    - /tmp/default.conf:/etc/nginx/conf.d/default.conf
    - /tmp/laravel_project:/var/project
